<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('items', function (Blueprint $table) {
            // Drop the unique index on barcode to allow system-wide identical barcodes
            // Index name generated by Laravel for unique on column `barcode` is `items_barcode_unique`.
            if (Schema::hasColumn('items', 'barcode')) {
                $table->dropUnique('items_barcode_unique');
            }
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('items', function (Blueprint $table) {
            if (Schema::hasColumn('items', 'barcode')) {
                $table->unique('barcode');
            }
        });
    }
};
